server:
  port: 2002

spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: wangyaochong:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_storage
    username: wangyaochong
    password: qwerqwer

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml


seata:
  #  enable-auto-data-source-proxy: false
  tx-service-group: my-tx-group
  service:
    grouplist:
      #      default: wangyaochong:8091
      default: 127.0.0.1:8091
    vgroup-mapping:
      my-tx-group: default
  enabled: true
  application-id: ${spring.application.name}
  config:
    type: file
